baseURL = 'https://hive.apache.org'
languageCode = 'en-us'
title = 'Hive Site'
theme = 'hive'
[params]
  hiveLogo = "/images/hive.svg"
  logo = "/images/asf_logo.png"
  apacheURL = 'https://www.apache.org'
  javaDocUrl = 'https://svn.apache.org/repos/infra/websites/production/hive/content/javadocs'

[params.banner]
    github = "https://github.com/apache/hive"
    docker = "https://hub.docker.com/r/apache/hive"
    jira = "https://issues.apache.org/jira/projects/HIVE/issues"

[params.apache]
    apacheUrl = "https://www.apache.org/"
    license = "https://www.apache.org/licenses/"
    howItWorks = "https://www.apache.org/foundation/how-it-works.html"
    privacyPolicy = "https://privacy.apache.org/policies/privacy-policy-public.html"
    apacheEvents = "https://www.apache.org/events/current-event"
    security = "https://www.apache.org/security/"
    sponsors = "https://www.apache.org/foundation/sponsorship.html"
    donate = "https://www.apache.org/foundation/contributing.html"
    copyright = "The contents of this website are Â© 2023 Apache Software Foundation under the terms of the Apache License v2. Apache Hive and its logo are trademarks of the Apache Software Foundation."
    thanks = "https://www.apache.org/foundation/thanks.html"

[params.navbar]
    release = "/general/downloads"
    poweredby = "/general/poweredby/"
    javaDocs = "/docs/javadocs/"
    latest = "/docs/latest/"
    languageManual = "https://hive.apache.org/docs/latest/language/languagemanual"
    license2 = "https://www.apache.org/licenses/LICENSE-2.0.html"
    privacyPolicy = "/general/privacypolicy/"
    designDocs = "/development/desingdocs/"
    hiveJira = "https://issues.apache.org/jira/projects/HIVE/issues"
    faq = "https://hive.apache.org/community/resources/hivedeveloperfaq"
    vcs = "/development/versioncontrol/"
    committer = "/community/becomingcommitter/"
    contribute = "https://hive.apache.org/community/resources/howtocontribute"
    resourcesForDev = "/community/resources/"
    meetings = "/community/meetings/"
    mailinglists = "/community/mailinglists/"
    issueTracking = "/community/issuetracking/"
    people = "/community/people/"
    bylaws = "/community/bylaws/"
    howToRelease = "/community/resources/howtorelease/"
    gettingStarted = "/development/gettingstarted/"
    docker = "/development/quickstart/"
    blogs = "https://hive.blog.apache.org/"
    announcements = "/general/downloads/#23-november-2025--release-420-available"

[params.features]
    acidTxn = "https://hive.apache.org/docs/latest/user/hive-transactions"
    hs2 = "https://hive.apache.org/docs/latest/user/hiveserver2-overview"
    hms = "https://hive.apache.org/development/desingdocs/design"
    compactions = "https://hive.apache.org/docs/latest/language/languagemanual-ddl#alter-tablepartition-compact"
    repl = "https://hive.apache.org/docs/latest/admin/replication"
    cbo = "https://hive.apache.org/docs/latest/user/cost-based-optimization-in-hive"
    llap = "https://hive.apache.org/development/desingdocs/llap"
    iceberg = "https://iceberg.apache.org/docs/latest/hive/"

[outputs]
    home = ["HTML", "RSS", "JSON"]
[markup]
    [markup.tableOfContents]
        endLevel = 3
        ordered = false
# Ideally we should start from level 2 but various pages
# contain multiple level-1 headers at the moment that
# should be displayed in the table of contents
        startLevel = 1
